### ISSUE TITLE
Target Sum Leetcode 

### ISSUE THREAD

**Issue by Arjun-1111111** [Arjun-1111111/Algorithm-_with_cpp#4]

**Comment by PradyumnG** [comment]
Hello @Arjun-1111111, I want to contribute and fix this issue. Please assign it to me.

**Comment by Arjun-1111111** [comment]
@PradyumnG I assign it to you , go ahead

**Comment by roastedcoder** [comment]
Hello @Arjun-1111111, I have made a PR, Please review it

**Comment by PradyumnG** [comment]
Thanks for assigning it to me @Arjun-1111111 .
